baseURL: https://shirazkn.github.io
languageCode: en-us
title: Shiraz
theme: PaperMod
publishDir: docs
params:
  homeInfoParams:
    Title: "under construction..."
    Content: "Please leave a comment!"

  socialIcons: # optional
    - name: "Github"
      url: "https://www.github.com/shirazkn"
    - name: "Self-reference"
      url: "https://www.shiraz-k.com"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "/favicon.ico"
  math: true
  
menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
