baseURL: https://shirazkn.github.io
languageCode: en-us
title: Shiraz
theme: PaperMod
publishDir: docs
params:
  env: production
  
  homeInfoParams:
    Title:

  socialIcons: # optional
    - name: "Github"
      url: "https://www.github.com/shirazkn"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/shiraz-k/"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "/favicon.ico"
  
  math: true

  comments: true

  fuseOpts:
    isCaseSensitive: false
    ignoreDiacritics: true
    shouldSort: true
    findAllMatches: false
    # location: 0
    # distance: 1000
    threshold: 0.1
    minMatchCharLength: 3
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "content"]

  
menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - $
            - $
          - - \(
            - \)
        enable: true
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
