baseURL: https://shirazkn.github.io
languageCode: en-us
title: Shiraz
theme: PaperMod
publishDir: docs
params:
  env: production
  
  homeInfoParams:
    Title:

  socialIcons: # optional
    - name: "Github"
      url: "https://www.github.com/shirazkn"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/shiraz-k/"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "/favicon.ico"
  math: true

  comments: true
  
menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
markup:
  goldmark:
    renderer:
      unsafe: true